blank_issues_enabled: false
contact_links:
  - name: General support request or other project-relasted question
    url: https://groups.io/g/openwebrx
    about: Request help on the community mailing list
